//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Universal Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UniversalInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UniversalInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Universal Input"",
    ""maps"": [
        {
            ""name"": ""Universal Map"",
            ""id"": ""6ef11e9e-d2e7-45e6-ba40-29fa55eaae4d"",
            ""actions"": [
                {
                    ""name"": ""LStickUpDown"",
                    ""type"": ""Value"",
                    ""id"": ""73574459-143d-4570-b051-26545749ccba"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RStickUpDown"",
                    ""type"": ""Value"",
                    ""id"": ""ff311a42-2024-4f51-b657-cd40e51bfe13"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LStickLeftRight"",
                    ""type"": ""Value"",
                    ""id"": ""507cdcb7-fd8a-4ee4-9105-a4c7cc86d8eb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RStickLeftRight"",
                    ""type"": ""Value"",
                    ""id"": ""46538b42-29c1-43e9-96c7-337ff3759822"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause/Menu"",
                    ""type"": ""Button"",
                    ""id"": ""7a260ac8-8e21-44e6-b83d-82c0fd260cb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""35ec55fa-49ac-4f50-9158-d3ae52ea238c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""9c6b4516-a8c0-473e-8b02-86c18f732173"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBumper"",
                    ""type"": ""Button"",
                    ""id"": ""957517f5-af47-4079-a2a1-402a5a4ea0e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBumper"",
                    ""type"": ""Button"",
                    ""id"": ""73e920b0-3236-4c1a-93b3-5bbb613ce098"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadUp"",
                    ""type"": ""Button"",
                    ""id"": ""fce50732-1edc-48df-9e7f-f210510eb3ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadDown"",
                    ""type"": ""Button"",
                    ""id"": ""b733a2d4-bd48-42a9-bda5-df1c8fd36ec4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f92578d9-d55f-4bb7-bb12-be7aae64b20d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadRight"",
                    ""type"": ""Button"",
                    ""id"": ""dc843b9f-edf8-4d7e-9fdd-66c7f35fb058"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select/Share"",
                    ""type"": ""Button"",
                    ""id"": ""c8fe3d87-90cc-4a39-8ef7-ce0e4c5b9acd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A/X"",
                    ""type"": ""Button"",
                    ""id"": ""188ad9a0-71f5-433e-911f-f1e177a7a7a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B/Circle"",
                    ""type"": ""Button"",
                    ""id"": ""0bea74f2-f580-4f32-94ee-f81491856b5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X/Square"",
                    ""type"": ""Button"",
                    ""id"": ""e0cacfb4-b76b-40b6-9d9a-cc31726bebfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y/Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""d670d098-55e8-47ca-860c-e7da269a1595"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""6d3515b8-ef84-413e-9c56-566f1171b8c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RStickPress"",
                    ""type"": ""Button"",
                    ""id"": ""896c4761-4ef0-4b3d-a48c-b9592111abbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LStick"",
                    ""type"": ""Value"",
                    ""id"": ""aa75478c-05b7-4dda-a6f2-4467739cd224"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""25cb9000-14f4-4031-83ff-aa087d13cbf4"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f462fa13-0113-4db6-952c-aeb0868583cf"",
                    ""path"": ""<DualShockGamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55adb7f6-3283-4936-b8d6-8526090b9998"",
                    ""path"": ""<DualSenseGamepadHID>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01155c06-d570-477b-97e6-b14339e06fd5"",
                    ""path"": ""<XInputController>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""732899f7-3fcf-4034-8775-1b894fd28d64"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e72fb038-ad10-4651-a116-eb30fc7873d1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1ebc02d8-0736-4b6a-ad0f-03d73b8db7ad"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6619dee5-79e4-4516-ab78-2cf7df00bf59"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f650758-b532-4ea5-815a-e3ce21ee51d7"",
                    ""path"": ""<DualShockGamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08242f3f-4268-4db9-b38d-2223d2c0647f"",
                    ""path"": ""<DualSenseGamepadHID>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""685e2378-d179-46bd-9c14-1c32d90c4f48"",
                    ""path"": ""<XInputController>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a73174e7-765f-420d-8141-e2804bf39c9d"",
                    ""path"": ""<XInputController>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""a5ca6318-378e-4224-be5f-e7c3f66a9574"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""10a833c5-6aae-4f87-b224-67c047d71317"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""77576dc2-55ae-4265-a3f9-ea8b9b601015"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""77786991-9382-4562-ac48-9bb0afe39ed0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf70b64-ba2b-4275-960c-6e5c7cd2d201"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""199de235-8365-4616-95df-952a990577b8"",
                    ""path"": ""<DualSenseGamepadHID>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5c4efa6-623d-4b67-b00f-f05d3784448a"",
                    ""path"": ""<DualShockGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""137fadf3-c248-4ee9-a668-0ee753b7a7de"",
                    ""path"": ""<DualSenseGamepadHID>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""309569fc-5757-4622-91a5-f88d5477d7ad"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9acaa1f4-7e60-470c-a310-a49f96e1daee"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Pause/Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""122aafc7-8cef-40df-859c-d5bf9ce852fe"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d720f595-f521-4b08-bd62-b867202f8e89"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99dd0e73-0ecd-4859-8a0b-99636197c7fb"",
                    ""path"": ""<DualSenseGamepadHID>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f09ca46-f35a-45eb-ae10-5fd26dc0579f"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1f9c54a-16d0-42a8-b05f-1a3caa34cefb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d4136bd-e281-4bb3-9ae6-b63f7da5a45f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""245dd70f-3760-4163-8451-51b9aef584a0"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21574bc2-06ee-4ce6-87e3-44e3e557fb99"",
                    ""path"": ""<DualSenseGamepadHID>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4fce051-210b-45ce-9475-fd3bcb43db27"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23bb1f63-8173-462b-aa27-cac652c2df0e"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ecac353-81c2-41ed-bb52-0cdbfeb9081f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03b15bf4-ab07-49cc-bb60-9d70b06592b5"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2ccc45e-703f-478d-bd44-ccc289ec09a5"",
                    ""path"": ""<DualSenseGamepadHID>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4761dd7d-4b94-42d5-b617-26b1e6a7e9cc"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37d30841-7aa8-4450-a83a-afaebce249a3"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28a58cc1-c450-4f19-8951-a34b36acb729"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79850219-e232-48ae-ae07-4b62940bccb3"",
                    ""path"": ""<DualSenseGamepadHID>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""012de413-0017-477e-94c3-92cf076ab7f6"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f31e8a17-60c0-4794-ac99-c29ebbd61b2c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ec011b-cb17-4d20-96ba-254264bcb6dd"",
                    ""path"": ""<DualShockGamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d194dafa-72eb-4b14-91c0-9b6ed7c62e2c"",
                    ""path"": ""<DualSenseGamepadHID>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a49c333c-c089-468e-b98f-305b9d70d84a"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4052bf64-2c15-4390-b6ca-7b79250bf890"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92e809df-0f4e-41c0-832f-09de00c145f6"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""439d8a32-dd9d-4be2-8bc8-bc16daa5dafd"",
                    ""path"": ""<DualSenseGamepadHID>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""486f2501-093a-41aa-a97a-bc86fe685de0"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bf164f8-2116-44ea-a18c-58f1b8b5128d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b76d1f2c-6031-4ee0-bcfd-e930ad8286c3"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c70f2833-0084-4418-9320-d0a1105bc365"",
                    ""path"": ""<DualSenseGamepadHID>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c40be922-1cb3-47b2-9574-62672e0b04bc"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97bf0118-270b-4c83-b08f-576995976c9b"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Select/Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7304aa4f-7792-4c70-af02-638a9388465e"",
                    ""path"": ""<DualShockGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Select/Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""722cf231-35f6-41cd-a888-0d62255816cf"",
                    ""path"": ""<DualSenseGamepadHID>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Select/Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e17ae8a-97df-4cb3-a9c6-28222b2849f0"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Select/Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b59ac02f-0d91-472a-bc10-ca74697384be"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""A/X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f60663f-5e04-4ee4-82c8-e51c152affd8"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""A/X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6dc1f4d-e240-44ef-8965-53b377e78d4d"",
                    ""path"": ""<DualSenseGamepadHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""A/X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""deb0e495-ae22-4b60-b06e-f87b871229ca"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""A/X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e562205-f086-45f8-bb7d-1c0478cb4aaa"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""A/X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36a14b17-47d8-4695-ae1d-eb9aec873be5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""B/Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ca4594d-67f7-46a3-845b-9abbde657cb8"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""B/Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c57df71-8b14-4d38-bff6-e6ba6f71e08f"",
                    ""path"": ""<DualSenseGamepadHID>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""B/Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eec83d2-6b58-4008-a8ab-7bb05b521f6d"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""B/Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98b36144-6d91-4b94-915d-c42537c8070c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""B/Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13accc80-510a-430b-9e32-d506248d22da"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""X/Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8004b757-b5bc-49e8-bf88-b11c94705435"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""X/Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73296eba-448f-4eb5-a4e8-c5a3e3cb9809"",
                    ""path"": ""<DualSenseGamepadHID>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""X/Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e51909f-7a53-4161-a3c8-a9fb4ce800ca"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""X/Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a5df988-5c15-42f1-8436-c2c8cdb74256"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""X/Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13639dd3-d8c9-4410-a13e-900aca4c1095"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Y/Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed5a7b8c-84d9-4d89-8448-c8c41d2ee060"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Y/Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c69a32e-e51f-4af9-83a0-766226653d49"",
                    ""path"": ""<DualSenseGamepadHID>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Y/Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff32335a-d034-4d4b-a8b6-00acaa271f8f"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""Y/Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a5a8553-90c7-49e6-aa40-a707b18b92f5"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09ae0991-c298-4fb7-8fb7-5d79b4538c5a"",
                    ""path"": ""<DualShockGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6161a4c5-5344-4d5a-a34a-2d50d9d79c5f"",
                    ""path"": ""<DualSenseGamepadHID>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c12793ee-377a-43b9-885e-28a0c50476c1"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""LStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32453868-3030-4e55-ad6d-28824dc0065e"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37f20b3f-93a9-41d8-af4a-0bf27ef65369"",
                    ""path"": ""<DualShockGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0830ecc7-73bc-41bc-b6a2-95196e1559b5"",
                    ""path"": ""<DualSenseGamepadHID>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13d2b4c9-7a1c-4cf6-9b05-273d1321f8c3"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a25f449e-966b-4eb3-8aab-646773ec9605"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3893595-f500-4726-b3a5-03fbff479852"",
                    ""path"": ""<DualShockGamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6828236f-822d-463c-9fa3-4a660d5e8984"",
                    ""path"": ""<DualSenseGamepadHID>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""072a26bd-b0c7-4d9c-ae8a-4b22af2fe010"",
                    ""path"": ""<XInputController>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31be44e8-e942-4c6d-8bfc-6eb34b4beea4"",
                    ""path"": ""<Mouse>/position/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickUpDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""867ee777-0ad4-4359-994c-d73db8f4dfc9"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9b75ce7-fd89-4636-b9da-a76656912f0a"",
                    ""path"": ""<DualShockGamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b418bf23-c2b9-4194-8254-d7e0c16d5121"",
                    ""path"": ""<DualSenseGamepadHID>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7f80b01-681d-413d-aec0-40ed593f8182"",
                    ""path"": ""<XInputController>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.125)"",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40d8bdd1-b97c-492f-9a94-84519e88b994"",
                    ""path"": ""<Mouse>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RStickLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6246c0bc-0cf6-4f1d-9190-e4060dc02a88"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bff0fe83-9926-40a1-9afa-0aead78c0a50"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa3ea7f0-5d30-4a5a-b250-a955731a8999"",
                    ""path"": ""<DualSenseGamepadHID>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c5da8f3-f529-4f54-9bde-16f795f11a1c"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f59176ac-050a-44e2-a35f-da6a93b797b3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Universal"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3010311-3c18-44b2-96d6-67a939caf340"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad037c4e-8198-407e-afb3-178bdb80e335"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a34da8a-7b57-408e-bada-b46ea107ebda"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c05557ad-bd77-4cdc-8423-fb04635bacc3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea4a62a6-6a9e-44ce-aa4b-bbbcd404fac8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""67f9568f-09c8-4ee0-95aa-684aa6c549a5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ee6a776f-0d7f-4d74-a4da-82ee96defda2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d0a121ac-f5dc-44ce-bf37-6430ae6929cf"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d858c75f-4c63-4e81-8255-53308dc9e761"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2739d938-dbb8-4b70-9ffc-decbac444fe9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Universal"",
            ""bindingGroup"": ""Universal"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualSenseGamepadHID>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Universal Map
        m_UniversalMap = asset.FindActionMap("Universal Map", throwIfNotFound: true);
        m_UniversalMap_LStickUpDown = m_UniversalMap.FindAction("LStickUpDown", throwIfNotFound: true);
        m_UniversalMap_RStickUpDown = m_UniversalMap.FindAction("RStickUpDown", throwIfNotFound: true);
        m_UniversalMap_LStickLeftRight = m_UniversalMap.FindAction("LStickLeftRight", throwIfNotFound: true);
        m_UniversalMap_RStickLeftRight = m_UniversalMap.FindAction("RStickLeftRight", throwIfNotFound: true);
        m_UniversalMap_PauseMenu = m_UniversalMap.FindAction("Pause/Menu", throwIfNotFound: true);
        m_UniversalMap_LTrigger = m_UniversalMap.FindAction("LTrigger", throwIfNotFound: true);
        m_UniversalMap_RTrigger = m_UniversalMap.FindAction("RTrigger", throwIfNotFound: true);
        m_UniversalMap_LBumper = m_UniversalMap.FindAction("LBumper", throwIfNotFound: true);
        m_UniversalMap_RBumper = m_UniversalMap.FindAction("RBumper", throwIfNotFound: true);
        m_UniversalMap_DpadUp = m_UniversalMap.FindAction("DpadUp", throwIfNotFound: true);
        m_UniversalMap_DpadDown = m_UniversalMap.FindAction("DpadDown", throwIfNotFound: true);
        m_UniversalMap_DpadLeft = m_UniversalMap.FindAction("DpadLeft", throwIfNotFound: true);
        m_UniversalMap_DpadRight = m_UniversalMap.FindAction("DpadRight", throwIfNotFound: true);
        m_UniversalMap_SelectShare = m_UniversalMap.FindAction("Select/Share", throwIfNotFound: true);
        m_UniversalMap_AX = m_UniversalMap.FindAction("A/X", throwIfNotFound: true);
        m_UniversalMap_BCircle = m_UniversalMap.FindAction("B/Circle", throwIfNotFound: true);
        m_UniversalMap_XSquare = m_UniversalMap.FindAction("X/Square", throwIfNotFound: true);
        m_UniversalMap_YTriangle = m_UniversalMap.FindAction("Y/Triangle", throwIfNotFound: true);
        m_UniversalMap_LStickPress = m_UniversalMap.FindAction("LStickPress", throwIfNotFound: true);
        m_UniversalMap_RStickPress = m_UniversalMap.FindAction("RStickPress", throwIfNotFound: true);
        m_UniversalMap_LStick = m_UniversalMap.FindAction("LStick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Universal Map
    private readonly InputActionMap m_UniversalMap;
    private IUniversalMapActions m_UniversalMapActionsCallbackInterface;
    private readonly InputAction m_UniversalMap_LStickUpDown;
    private readonly InputAction m_UniversalMap_RStickUpDown;
    private readonly InputAction m_UniversalMap_LStickLeftRight;
    private readonly InputAction m_UniversalMap_RStickLeftRight;
    private readonly InputAction m_UniversalMap_PauseMenu;
    private readonly InputAction m_UniversalMap_LTrigger;
    private readonly InputAction m_UniversalMap_RTrigger;
    private readonly InputAction m_UniversalMap_LBumper;
    private readonly InputAction m_UniversalMap_RBumper;
    private readonly InputAction m_UniversalMap_DpadUp;
    private readonly InputAction m_UniversalMap_DpadDown;
    private readonly InputAction m_UniversalMap_DpadLeft;
    private readonly InputAction m_UniversalMap_DpadRight;
    private readonly InputAction m_UniversalMap_SelectShare;
    private readonly InputAction m_UniversalMap_AX;
    private readonly InputAction m_UniversalMap_BCircle;
    private readonly InputAction m_UniversalMap_XSquare;
    private readonly InputAction m_UniversalMap_YTriangle;
    private readonly InputAction m_UniversalMap_LStickPress;
    private readonly InputAction m_UniversalMap_RStickPress;
    private readonly InputAction m_UniversalMap_LStick;
    public struct UniversalMapActions
    {
        private @UniversalInput m_Wrapper;
        public UniversalMapActions(@UniversalInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @LStickUpDown => m_Wrapper.m_UniversalMap_LStickUpDown;
        public InputAction @RStickUpDown => m_Wrapper.m_UniversalMap_RStickUpDown;
        public InputAction @LStickLeftRight => m_Wrapper.m_UniversalMap_LStickLeftRight;
        public InputAction @RStickLeftRight => m_Wrapper.m_UniversalMap_RStickLeftRight;
        public InputAction @PauseMenu => m_Wrapper.m_UniversalMap_PauseMenu;
        public InputAction @LTrigger => m_Wrapper.m_UniversalMap_LTrigger;
        public InputAction @RTrigger => m_Wrapper.m_UniversalMap_RTrigger;
        public InputAction @LBumper => m_Wrapper.m_UniversalMap_LBumper;
        public InputAction @RBumper => m_Wrapper.m_UniversalMap_RBumper;
        public InputAction @DpadUp => m_Wrapper.m_UniversalMap_DpadUp;
        public InputAction @DpadDown => m_Wrapper.m_UniversalMap_DpadDown;
        public InputAction @DpadLeft => m_Wrapper.m_UniversalMap_DpadLeft;
        public InputAction @DpadRight => m_Wrapper.m_UniversalMap_DpadRight;
        public InputAction @SelectShare => m_Wrapper.m_UniversalMap_SelectShare;
        public InputAction @AX => m_Wrapper.m_UniversalMap_AX;
        public InputAction @BCircle => m_Wrapper.m_UniversalMap_BCircle;
        public InputAction @XSquare => m_Wrapper.m_UniversalMap_XSquare;
        public InputAction @YTriangle => m_Wrapper.m_UniversalMap_YTriangle;
        public InputAction @LStickPress => m_Wrapper.m_UniversalMap_LStickPress;
        public InputAction @RStickPress => m_Wrapper.m_UniversalMap_RStickPress;
        public InputAction @LStick => m_Wrapper.m_UniversalMap_LStick;
        public InputActionMap Get() { return m_Wrapper.m_UniversalMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UniversalMapActions set) { return set.Get(); }
        public void SetCallbacks(IUniversalMapActions instance)
        {
            if (m_Wrapper.m_UniversalMapActionsCallbackInterface != null)
            {
                @LStickUpDown.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickUpDown;
                @LStickUpDown.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickUpDown;
                @LStickUpDown.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickUpDown;
                @RStickUpDown.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickUpDown;
                @RStickUpDown.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickUpDown;
                @RStickUpDown.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickUpDown;
                @LStickLeftRight.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickLeftRight;
                @LStickLeftRight.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickLeftRight;
                @LStickLeftRight.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickLeftRight;
                @RStickLeftRight.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickLeftRight;
                @RStickLeftRight.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickLeftRight;
                @RStickLeftRight.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickLeftRight;
                @PauseMenu.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnPauseMenu;
                @PauseMenu.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnPauseMenu;
                @LTrigger.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLTrigger;
                @LTrigger.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLTrigger;
                @LTrigger.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLTrigger;
                @RTrigger.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRTrigger;
                @RTrigger.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRTrigger;
                @RTrigger.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRTrigger;
                @LBumper.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLBumper;
                @LBumper.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLBumper;
                @LBumper.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLBumper;
                @RBumper.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRBumper;
                @RBumper.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRBumper;
                @RBumper.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRBumper;
                @DpadUp.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadUp;
                @DpadUp.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadUp;
                @DpadUp.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadUp;
                @DpadDown.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadDown;
                @DpadDown.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadDown;
                @DpadDown.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadDown;
                @DpadLeft.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadLeft;
                @DpadLeft.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadLeft;
                @DpadLeft.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadLeft;
                @DpadRight.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadRight;
                @DpadRight.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadRight;
                @DpadRight.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnDpadRight;
                @SelectShare.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnSelectShare;
                @SelectShare.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnSelectShare;
                @SelectShare.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnSelectShare;
                @AX.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnAX;
                @AX.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnAX;
                @AX.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnAX;
                @BCircle.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnBCircle;
                @BCircle.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnBCircle;
                @BCircle.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnBCircle;
                @XSquare.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnXSquare;
                @XSquare.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnXSquare;
                @XSquare.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnXSquare;
                @YTriangle.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnYTriangle;
                @YTriangle.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnYTriangle;
                @YTriangle.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnYTriangle;
                @LStickPress.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickPress;
                @LStickPress.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickPress;
                @LStickPress.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStickPress;
                @RStickPress.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickPress;
                @RStickPress.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickPress;
                @RStickPress.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnRStickPress;
                @LStick.started -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStick;
                @LStick.performed -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStick;
                @LStick.canceled -= m_Wrapper.m_UniversalMapActionsCallbackInterface.OnLStick;
            }
            m_Wrapper.m_UniversalMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LStickUpDown.started += instance.OnLStickUpDown;
                @LStickUpDown.performed += instance.OnLStickUpDown;
                @LStickUpDown.canceled += instance.OnLStickUpDown;
                @RStickUpDown.started += instance.OnRStickUpDown;
                @RStickUpDown.performed += instance.OnRStickUpDown;
                @RStickUpDown.canceled += instance.OnRStickUpDown;
                @LStickLeftRight.started += instance.OnLStickLeftRight;
                @LStickLeftRight.performed += instance.OnLStickLeftRight;
                @LStickLeftRight.canceled += instance.OnLStickLeftRight;
                @RStickLeftRight.started += instance.OnRStickLeftRight;
                @RStickLeftRight.performed += instance.OnRStickLeftRight;
                @RStickLeftRight.canceled += instance.OnRStickLeftRight;
                @PauseMenu.started += instance.OnPauseMenu;
                @PauseMenu.performed += instance.OnPauseMenu;
                @PauseMenu.canceled += instance.OnPauseMenu;
                @LTrigger.started += instance.OnLTrigger;
                @LTrigger.performed += instance.OnLTrigger;
                @LTrigger.canceled += instance.OnLTrigger;
                @RTrigger.started += instance.OnRTrigger;
                @RTrigger.performed += instance.OnRTrigger;
                @RTrigger.canceled += instance.OnRTrigger;
                @LBumper.started += instance.OnLBumper;
                @LBumper.performed += instance.OnLBumper;
                @LBumper.canceled += instance.OnLBumper;
                @RBumper.started += instance.OnRBumper;
                @RBumper.performed += instance.OnRBumper;
                @RBumper.canceled += instance.OnRBumper;
                @DpadUp.started += instance.OnDpadUp;
                @DpadUp.performed += instance.OnDpadUp;
                @DpadUp.canceled += instance.OnDpadUp;
                @DpadDown.started += instance.OnDpadDown;
                @DpadDown.performed += instance.OnDpadDown;
                @DpadDown.canceled += instance.OnDpadDown;
                @DpadLeft.started += instance.OnDpadLeft;
                @DpadLeft.performed += instance.OnDpadLeft;
                @DpadLeft.canceled += instance.OnDpadLeft;
                @DpadRight.started += instance.OnDpadRight;
                @DpadRight.performed += instance.OnDpadRight;
                @DpadRight.canceled += instance.OnDpadRight;
                @SelectShare.started += instance.OnSelectShare;
                @SelectShare.performed += instance.OnSelectShare;
                @SelectShare.canceled += instance.OnSelectShare;
                @AX.started += instance.OnAX;
                @AX.performed += instance.OnAX;
                @AX.canceled += instance.OnAX;
                @BCircle.started += instance.OnBCircle;
                @BCircle.performed += instance.OnBCircle;
                @BCircle.canceled += instance.OnBCircle;
                @XSquare.started += instance.OnXSquare;
                @XSquare.performed += instance.OnXSquare;
                @XSquare.canceled += instance.OnXSquare;
                @YTriangle.started += instance.OnYTriangle;
                @YTriangle.performed += instance.OnYTriangle;
                @YTriangle.canceled += instance.OnYTriangle;
                @LStickPress.started += instance.OnLStickPress;
                @LStickPress.performed += instance.OnLStickPress;
                @LStickPress.canceled += instance.OnLStickPress;
                @RStickPress.started += instance.OnRStickPress;
                @RStickPress.performed += instance.OnRStickPress;
                @RStickPress.canceled += instance.OnRStickPress;
                @LStick.started += instance.OnLStick;
                @LStick.performed += instance.OnLStick;
                @LStick.canceled += instance.OnLStick;
            }
        }
    }
    public UniversalMapActions @UniversalMap => new UniversalMapActions(this);
    private int m_UniversalSchemeIndex = -1;
    public InputControlScheme UniversalScheme
    {
        get
        {
            if (m_UniversalSchemeIndex == -1) m_UniversalSchemeIndex = asset.FindControlSchemeIndex("Universal");
            return asset.controlSchemes[m_UniversalSchemeIndex];
        }
    }
    public interface IUniversalMapActions
    {
        void OnLStickUpDown(InputAction.CallbackContext context);
        void OnRStickUpDown(InputAction.CallbackContext context);
        void OnLStickLeftRight(InputAction.CallbackContext context);
        void OnRStickLeftRight(InputAction.CallbackContext context);
        void OnPauseMenu(InputAction.CallbackContext context);
        void OnLTrigger(InputAction.CallbackContext context);
        void OnRTrigger(InputAction.CallbackContext context);
        void OnLBumper(InputAction.CallbackContext context);
        void OnRBumper(InputAction.CallbackContext context);
        void OnDpadUp(InputAction.CallbackContext context);
        void OnDpadDown(InputAction.CallbackContext context);
        void OnDpadLeft(InputAction.CallbackContext context);
        void OnDpadRight(InputAction.CallbackContext context);
        void OnSelectShare(InputAction.CallbackContext context);
        void OnAX(InputAction.CallbackContext context);
        void OnBCircle(InputAction.CallbackContext context);
        void OnXSquare(InputAction.CallbackContext context);
        void OnYTriangle(InputAction.CallbackContext context);
        void OnLStickPress(InputAction.CallbackContext context);
        void OnRStickPress(InputAction.CallbackContext context);
        void OnLStick(InputAction.CallbackContext context);
    }
}
